services:
  ibge-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_PATH=/data/ibge.db
    # volumes:
    #   - ./data:/data:ro
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          # cpus: "1.0"
          cpus: "0.5"
        reservations:
          memory: 256M
          # cpus: "0.25"
    healthcheck:
      test: ["CMD", "/ibge-service", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
